[book]
authors = ["Jeaye Wilkerson"]
language = "en"
src = "src"
title = "The jank Programming Language"

[build]
build-dir = "live"
create-missing = false

[output.html]
admonitions = true
git-repository-url = "https://github.com/jank-lang/jank"
