name: Build book

on:
  push:
    branches:
      - main
    paths:
      - 'book/**'

permissions:
  contents: read

# Only allow one build per branch at a time. New builds will cancel existing builds.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-book:
    name: Build and publish book
    runs-on: ubuntu-24.04
    if: github.ref == 'refs/heads/main'
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: book
      - uses: awalsh128/cache-apt-pkgs-action@5902b33ae29014e6ca012c5d8025d4346556bd40
        with:
          packages: mdbook
          # Increment this when the package list changes.
          version: 1
      - name: Build and publish
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          pushd ${{ github.workspace }}/book
            ./bin/publish
          popd
